before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: H/ojiUAgEsM+2/JVCSduK+SULsNMdbsgPf7Nh+6Ds81SqUyaitTn2OrvqIpcRoVw3y2MJcsTeEvkZ3FB89HvdVpNxjBl9wQlciyoxwV04HnF9YKsX4k4xNbP938E+alYCxzwBAabadupUvsoVEUDIOsARjsXcFDPDQeCEjAAfl0KYPda4lsQCcl2NC5ysodx0iIVYy9CZ/fNwwqzHfkehagUIDDuv/PLlKOKnR6hWUZUdj6w4wp3ZhmGZGRFDYrE7zOxn1EWbSpp/WS7JERHIg0BBNjAfJfFU5HReE0DI6Uk0upBLy+/sHkd4mBnbtGjGv51vTGOij0pnNvkZFcMLpe6/W38c4L0Q52OcNOYNL93W6cQmEiT5ASogg52dvK+FhEN/cYnHWbhpBIpN+O4mUk2JEKP08iUP5pLAHFQwHw5uBWr3mLq3d/QkImX0uOc+R3eaM+qftHk4Vv/+x2fkVm3dz79ALbgHSpLzGCxJVdB86TZaDtKTEb991y2Sp591yJFVBg3vRUJByVTyGXMgAoYq++wlfFQXEum445a1qAQN0GuN1vyDqn3vKvdv2oWGPn/Qwz1O+oqf0wRM5qFW99iX0TD2gd6w1tIJ3uDqHYqpaQAHxKZV3xV0T7OK1My281JYIISk6AzniR5HXGh5j76v/o0PAdiDFAjAkL44iQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
